# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ghcT2ymA0EN16UYEiMnyxf2-IYOgE7t
"""



def tashxis(belgi):
  if belgi=="Istma":
    return "Parastamol iching"
  elif belgi == "Bosh og'rig'i":
    return "Bol nol iching"
  elif belgi == "Tish og'rig'i":
    return "Bol nol iching"
  else:
    return "Shifokorga murojat qiling"
belgi=input("Kasalik belgisini kiriting")
natija=tashxis(belgi)
print(natija)

def kino(janr):
  if janr=="Fentezi":
    return "Uzuklar hukumdori"
  elif janr == "Drama":
    return "Samo farzandlari"
  elif janr == "Milliy kino":
    return "Osmondagi bolalar"
  else:
    return "Janr topilmadi"
janr=input("Janrni tanlang")
natija=kino(janr)
print(natija)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2

def kino(janr):
  if janr=="Fentezi":
    rasm=cv2.imread('uzuklarh.webp')
    cv2_imshow(rasm)
    return "Uzuklar hukumdori"
  elif janr == "Drama":
    rasm=cv2.imread('samo_f.jpg')
    cv2_imshow(rasm)
    return "Samo farzandlari"
  elif janr == "Milliy kino":
    rasm=cv2.imread('osmondagi_b.jpeg')
    cv2_imshow(rasm)
    return "Osmondagi bolalar"
  else:
    return "Janr topilmadi"
janr=input("Janrni tanlang")
natija=kino(janr)
print(natija)